CREATE DATABASE EMPLOYEE;
USE EMPLOYEE;
CREATE TABLE  EMPLOYEE_TBL
(
EMP_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
SALARY FLOAT,
MOBILE_NO VARCHAR(15)
);
INSERT INTO EMPLOYEE_TBL VALUES(5, 'MARA', 'SHURPC', 25000, '456CSC65956');
SELECT * FROM EMPLOYEE_TBL;
DELETE FROM EMPLOYEE_TBL WHERE EMP_ID=1;
UPDATE EMPLOYEE_TBL SET FIRST_NAME='RAJAT' WHERE EMP_ID = 3;